Разметка главной страницы
htmlacademy-htmlcss/1542653-technomart-29 pull request #2
Opened 2020-09-21 12:17 UTC by YourfriendRND

Выполнена разметка главной страницы проекта "Техномарт"

2020-09-22 06:14 UTC, lipa88-mk requested changes
В целом очень хорошо, немного нужно поправить распределение по секциям, с разметкой текста справились хорошо. Как внесете правки и отправите коммиты в этот же пуллреквест, в интерфейсе курса на сайте академии нужно нажать кнопку "Отправить на проверку"

2020-09-22 06:14 UTC, lipa88-mk commented on index.html
> +          </section>
По секциям немного не так - это всё - 1 секция. Но в ней есть еще 2 части- навигация и заголовок с текстом. Секцию можно сложить в другую секцию. Тут делаются вкладки - при клике на пункт меню слева справа появляется соответствующий этому пункту текст. 
ТЗ: Блок «Сервисы»: слайдер. Вёрстка всех слайдов обязательна. Блок «Сервисы»: оживление слайдера. Слайдер с табами работает аналогично слайдеру промо-блока: смена слайда происходит мгновенно при клике на соответствующий таб.

То есть там будет 3 блока - доставка, гарантия, кредит. Верстать нужно всё, реализовывать раюоту самого слайдера - дополнительно

2020-09-22 06:14 UTC, lipa88-mk commented on index.html
> +      </section>
Это всё тоже 1 секция, состоящая из 2х частей - левой и правой.
в 1м параграфе нао убрать лишний бр, из списка убрать тег strong - это добавится через стили. 

Справа: всё верно, только на IE мы не отвлекаемся, его нет в ТЗ. ТЗ: Блок карты: достаточная реализация — обычное изображение, клик по ней приводит к переходу на сервис карт.

2020-09-22 06:14 UTC, lipa88-mk commented on index.html
> +    <footer>
Подвал состоит из 2х частей, разных по цвету. В 1 части лучше делить одержимое по строчкам: 1 строка - лого и навигация белого цвета, 2 строка - адрес и навигация желтая. Это тоже могут быть секции, можно просто дивами.

2020-09-22 06:14 UTC, lipa88-mk commented on index.html
> +        </p>
А это всё - вторая часть подвала. состоит из 4 частей/колонок - копирайт, соцсети, обратная связь, разработано.

2020-09-22 13:59 UTC, lipa88-mk commented on catalog.html
>  <head>
Не торопитесь! Эта страница делается в другом задании!

2020-09-22 14:01 UTC, lipa88-mk commented on index.html
> +          <li><a href="#">Каталог</a></li>
ссылка с главной на каталог была правильной

2020-09-22 14:04 UTC, merged

2020-09-22 14:06 UTC, lipa88-mk commented
Не нужно вместе с правками закидывать и другое задание! Это приведет к тому, что другое задание будет не засчитать. Плюс получается путаница. 1 задача - правки только по этой задаче.

2020-09-23 07:45 UTC, YourfriendRND commented on index.html
> +          <li><a href="#">Каталог</a></li>
Объясню почему принял такое решение:
На внутренней странице есть мини-навигация которая показывает путь страницы, и там видно, что путь следующий:
Главная->Каталог->Инструмент->Перфораторы. 
Т.е. открыта страница с перфораторами, а не с общим каталогом товаров. Логически я понимаю, что на главной странице есть ссылка на общий каталог с товарами, а ниже на слайдере есть ссылка открывающая именно каталог с перфораторами (наша внутренняя страница) на которую я и делаю переход. Т.е. посетитель видит, что основной продукт или продукт к которому привлекают внимание это перфораторы и открывает каталог с ними, а если ему нужно, что-то другое, то он откроет общий каталог из которого тоже можно будет попасть в перфораторы. Если я думаю, как-то не правильно, пожалуйста, поясните, дайте верное понимание.

2020-09-23 07:56 UTC, lipa88-mk commented on index.html
> +          <li><a href="#">Каталог</a></li>
Да, мысль верная. Но тк это учебный макет и нам самим надо как-то перемещаться между страницами, а других внутренних у нас нет, то в данной ситуации можно оставить ссылку на единственную имеющуюся внутреннюю страницу. Если бы это был полный проект магазина, то конечно же да, нужно было бы делать ссылки на верные внутренние. В данном случае мы делаем допущение для своего удобства