Разметка внутренней страницы
htmlacademy-htmlcss/1542653-technomart-29 pull request #3
Opened 2020-09-23 13:18 UTC by YourfriendRND

Выполнена разметка внутренней страницы

2020-09-23 20:33 UTC, lipa88-mk requested changes
Не смогла написать комментарии к нужным строчкам, тк код страницы был в прошлом пулреквесте, так что пришлось писать все одним комментарием. Если будут вопросы - пишите, уточню.

2020-09-23 20:33 UTC, lipa88-mk commented on catalog.html
>  <html lang="ru">
лого в шапке - ссылка на главную. 
В блоке авторизованного посетителя имя и иконка пользователя являются ссылкой на профайл, а иконка выхода — на страницу деавторизации. - нужно добавить по ТЗ. Так же рекомендую обращаться к пунктам ТЗ, чтобы не упустить какое-то поведение элементов. Мало ли я где-то просмотрю. 

Список с хлебными крошками тоже можно сделать отдельной секцией. Но это позже можно будет добавить, если потребуется для сетки.

Часть с фильтром семантически можно определить как aside, например. 

В товарах в появляющемся блоке не нужно дублировать информацию - название и цена. Там будут только 2 кнопки, поведение их нужно уточнить в ТЗ - кнопки они или ссылки.
Пагинация после товаров - это всё кнопки, не ссылки, и  у 1й должен быть disabled, тк мы ее уже смотрим, нажимать ее не нужно

Ссылка в подвале htmlacademy.ru ведёт на лендинг интенсива «HTML и CSS. Профессиональная вёрстка сайтов». а Логотип — это ссылка на главную страницу.

2020-09-24 12:18 UTC, YourfriendRND commented on catalog.html
>  <html lang="ru">
Исправления внес, кроме хлебных крошек, если в дальнейшем потребуется, то добавим им секцию. 

>  товарах в появляющемся блоке не нужно дублировать информацию - название и цена. Там будут только 2 кнопки, поведение их нужно уточнить в ТЗ - кнопки они или ссылки.
Не вижу этого в ТЗ, я предполагаю, что это должны быть кнопки, так как при нажатии происходит либо добавление в закладки либо появляется модальное окно, о том что товар добавлен в корзину. 

Есть вопросы: 
1)Сортировка товара, это отдельная форма или это часть фильтра? Т.е. правильно ли ее добавлять в отдельную секцию? 
2) Пропустил в верстке момент где есть товары с меткой New, каким образом правильно ее добавить не могу понять, если можно дай совет, или можем отложить вопрос до живой консультации.

P.S. Добавил в коммит все измененные файлы, еще тренируюсь с гитом и понимаю, что иногда не понимаю что делаю, поэтому прошу не ругать :))

2020-09-24 17:41 UTC, lipa88-mk commented on catalog.html
>  <html lang="ru">
По хлебным крошкам да, хорошо. По вопросам: 1. Отдельная, будет новая часть, про это будет отдельная лекция, тк такие элементы есть во всех макетах
2. Это можно сделать подностью через стили и псевдоэлементы, можно на дальнейшем этапе работы со стилями обозначить эти товары отдельным классом, пока это не актуально, сначала будет работа с сеткой) 
По гиту - да, это понимаю, без проблем, понятно, что только учитесь, для этого вы и здесь)

2020-09-24 17:49 UTC, lipa88-mk requested changes
Убираем из  кода главной классы, тк они не относятся к этому заданию, и нужно поправить ссылку в шапке каталога для авторизованного пользователя. На этом задание будет готово и можно будет переходить к следующему.

2020-09-24 17:49 UTC, lipa88-mk commented on catalog.html
> +                <span> Равшан Джамшутович</span>
Имя тоже ссылка. То есть тег а нужно закрыть после имени и плюс в закрывающем теге лишний пробел

2020-09-24 17:49 UTC, lipa88-mk commented on index.html
> +      <section class="menu">
опять же - настоятельно прошу не заливать в повторную проверку то, что к ней не относится!

2020-09-25 19:00 UTC, merged

2020-09-25 19:02 UTC, lipa88-mk commented
Супер! Чтобы убирать из коммита то, что туда не должно было попасть, посмотрите подкасты в 1й части по гиту, там как раз разбирается эта ситуация, как убрать файл из коммита, чтобы его не редактировать туда-обратно.
https://up.htmlacademy.ru/htmlcss/29/module/1/screencasts/4 
https://up.htmlacademy.ru/htmlcss/29/module/1/screencasts/5