Стилизация главной страницы
htmlacademy-htmlcss/1542653-technomart-29 pull request #4
Opened 2020-09-28 13:24 UTC by YourfriendRND

Выполнена базовая стилизация главной страницы с учетом всех требований задания.

2020-09-28 13:24 UTC, YourfriendRND commented
В целом, считаю, что базовая стилизация выполнена. Мои комментарии к пунктам:

1. Добавление классов в разметку: 
Выполнено, возможно где-то не совсем корректные названия и можно, что-то улучшить
возможно, есть что-то лишнее. Нужны рекомендации, что улучшить. 

2. Подключение нестандартных шрифтов (локально или из сервиса):
Подключил локально. Хотелось бы понимать правильно ли и как лучше локально или через сервис? 

3.Подключение normalize.css (по желанию).
Подключил, это не энергозатратно. :)

4. Описание текстовых параметров для всех элементов.
Здесь нужно проверять, старался проверять каждый элемент. Возможно, нужно добавить какие-то еще правила. Но есть вопросы (см. ниже)

5. Описание фоновых параметров (фоновый цвет)
Нужно проверять, также старался уделить внимание всем элементам.

6. Описание состояний интерактивных элементов, которые описаны в стайлгайде. 
На этом этапе задавайте только текстовые параметры и параметры фона.
Выполнено. Нужно проверять.
 
7. Все цвета вынесены в кастомные свойства в селектор :root.
Вынес все цвета, но честно, сказать фантазии на придумывание названий этим цветам не хватило, называл как видел. Если порекомендуешь, 
что улучшить буду благодарен. 

Вопросы: 
1. Текст на кнопках в блоках инструменты, техника и т.д. не виден, получается он как будто на заднем фоне и соответственно, сейчас
текст не виден на кнопке. Как исправить этот момент? Не нашел решения. Нужен совет. 

2. В Блоках Популярные товары и Популярные производители задал цвет фона для всего блока, хотя фон есть только у загаловка и ссылки,
я мог бы выделить их в отдельный блок и задать фоновый цвет. Вопрос в том, можно ли оставить фон только заголовку и кнопке при этом 
убрать для остального контента каким-то другим способом не оборачивая их в отдельный блок?

3. В блоке "Сервисы" хотел сделать первый заголовок черным, а все остальные темно-синий цветом (по макету), но через псевдокласс :first-child
неполучилось это сделать. Оставил закомментированный код. Нужна подсказка как это сделать? Я конечно, мог бы добавить этому заголовку класс
и сделать его черным, но мне показалось это слишком просто и хотелось сделать это иначе. Возможно я усложняю.

2020-09-29 11:44 UTC, lipa88-mk requested changes
Очень хорошо, надо доразобраться с подключением шрифтов, сейчас шрифт везде Arial, плюс добавить normalize  в коммит. И проверить все заголовки - там жирность везде не та, нужна 400.
Проверить работоспособность шрифта можно с помощью валидатора https://jigsaw.w3.org/css-validator/ ошибок не должно быть. Плюс в отладчике хрома - Вкладка Elements - там где стили - вкладка Computed - в самом низу Rendered fonts - это и ест примененный в итоге шрифт

2020-09-29 11:44 UTC, lipa88-mk commented on index.html
> +    <link rel="stylesheet" href="css/Normalize.css">
Файл не найден, нужно загрузить. И по критерию Б14 - В названиях и расширениях файлов нет заглавных букв и пробелов, использованы только латинские символы. Т.е.название нужно поправить

2020-09-29 11:44 UTC, lipa88-mk commented on index.html
> +          <p class="slogan"> Интернет-магазин<br>
класс лучше переназвать, по критерию Д21 - Отсутствует транслит в названиях классов, атрибутах и так далее

2020-09-29 11:44 UTC, lipa88-mk commented on css/style.css
>      url('../fonts/ptsans.woff') format('woff');
В подключении шрифтов ошибка в строчке 8 и 16, нет запятой после local. Шрифт макета не работает, все написано запасным Arial

2020-09-29 11:44 UTC, lipa88-mk commented on index.html
> +      <h1 class="hidden">Интернет-магазин ТЕХНОМАРТ</h1>
Скрытые элементы уже на этом этапе можно скрыть, раз уж мы начали работать со стилями)

2020-09-29 11:44 UTC, lipa88-mk commented on index.html
> +          <a class="transparent-button" href="#">На любой вкус</a>
Тут opacity лишнее. Прозрачный на 30% только фон, не текст. Иначе в покое текста кнопки не видно.

2020-09-29 11:44 UTC, lipa88-mk commented on index.html
>                 <img src="#" alt="Кнопка переключения блоков">
что тут имеется в виду? Если это про стрелки перелистывания слайдов, то их должно быть 2 - налево и направо. Пока можно обозначить button  с текстом налево и направо внутри, стрелку можно сделать стилями, без применения картинок. Кнопке нужен свой класс.

2020-09-29 11:44 UTC, lipa88-mk commented on css/style.css
> +.popular-manufacturers h2 {
жирность шрифта не по макету во всех аналогичных заголовках, нужно поправить

2020-09-29 11:44 UTC, lipa88-mk commented on index.html
>              Рахработано - <br>
Опечатка в слове)

2020-09-29 12:00 UTC, lipa88-mk commented
По вопросам: 

по названиям классов - 1 комментарий написала, где нужно заменить транслит. Остальное верно.

Подключение нестандартных шрифтов (локально или из сервиса): лучше локально, но это сложнее, на данном этапе можно и по ссылке. Раз начали делать локально, то нужно исправить ошибки.



Все цвета вынесены в кастомные свойства в селектор :root. По названиям тут без разницы, лишь бы было понятно где оно применяется, все вполне нормльно

Вопросы:

Текст на кнопках в блоках инструменты, техника и т.д.  - написала

В Блоках Популярные товары и Популярные производители: я мог бы выделить их в отдельный блок и задать фоновый цвет. - Это верно, так и надо сделать

В блоке "Сервисы" хотел сделать первый заголовок черным, а все остальные темно-синий цветом (по макету) - вот тут я не очень поняла, что именно вы хотели сделать. В этом блоке есть заголовок 2 уровня Сервисы, далее заголовки должны быть уровня ниже. И лучше задать просто классы и через них нужные цвета.

2020-09-29 14:56 UTC, YourfriendRND commented
- Шрифты запустились;
- Нормолайз закоммитил;
- Кнопки получилось сделать прозрачные;
- Нужные классы поменял;
- Элементы необходимые скрыть - скрыл;
- Заголовки проверил, сделал необходимые по жирности;

2020-09-30 08:51 UTC, merged

2020-09-30 08:52 UTC, lipa88-mk commented
Отлично! Можно приступать к следующему заданию)