Стилизация внутренней страницы
htmlacademy-htmlcss/1542653-technomart-29 pull request #5
Opened 2020-10-01 10:02 UTC by YourfriendRND

Выполнена базовая стилизация страницы каталога.

2020-10-01 10:02 UTC, YourfriendRND commented
Считаю, что базовая стилизация страницы каталога выполнена. 
Есть моменты, которые не получились, не нашел путей решения: 
1) Название товара шрифт PT Sans, font-weight=700, у меня также, но отображается по факту не так как на макете. 
В папке со шрифтами есть PT Sans bold, подключать не пробовал, думаю, что ошибка где-то в тикущих стилях, но если нет, то подключу
и исправлю.
2) В пагинации рамка при нажатии должна быть красного цвета, в Mozil'е это успешно реализовано, в Chrom'е 
базовые стили почему-то переопределяют цвет рамки и как исправить это, не понятно. Подскажи, пожалуйста, как можно решить это. 
Спасибо!

2020-10-01 12:10 UTC, lipa88-mk requested changes
Нужно немного поправить, и разобраться с подключением шрифтов разных написаний (жирный, курсив)

2020-10-01 12:10 UTC, lipa88-mk commented on catalog.html
> +                <h1 class="main-headline">Перфораторы</h1>
В заголовках Перфоратор BOSCH BFG 6000 и далее жирность шрифта PT Sans не по макету

2020-10-01 12:10 UTC, lipa88-mk commented on catalog.html
> +                    <li><button class="order-button" type="button">Оформить заказ</button></li>
У всех button нужно убрать  стандартную рамку border. Тут и на главной тоже.

2020-10-01 12:10 UTC, lipa88-mk commented on catalog.html
> +                        <button class="pagination-button" type="button">3</button>
Используется PT Sans 400, но он не подключен

2020-10-01 12:10 UTC, lipa88-mk commented on catalog.html
> +                        <button class="pagination-button" type="button">Следующая</button>
Тут капсом через стили

2020-10-01 12:12 UTC, lipa88-mk commented
По вопросам: 1. нужно подкючить все написания шрифтов
2. при фокусе срабатывает не border, а outline

2020-10-02 09:59 UTC, YourfriendRND commented
Внес изменения. 
- Все шрифты подключены:
- Рамки у кнопок убрал в глобальных стилях, через outline: none;
- Для кнопок отдельно прописывал стили border, потому что во многом есть скругления радиуса границ, а через outline задать скругления нет возможности. 
Сейчас, уже не вижу, что можно улучшить или исправить.

2020-10-02 21:13 UTC, lipa88-mk requested changes
В целом верно, всё уже очень похоже на макет. Но пара моментов еще есть: 
1. Скругление border-radius работает и без border, оно действует так же и на фон. У зеленых кнопок так же остался border серый
2. Подключение нескольких написаний одного шрифта сделано не верно. 
font-family: 'Cuprum'; - одно и то же для всех написаний, font-family: 'Cuprum-bold' - неверно. 
Надо font-family: 'Cuprum'; и font-weight: 700; Когда нужно применить это написание, то так и пишем - семейство и жирность и/или курсив. 

Задание большое, поэтому нормально, что несколько проверок

2020-10-05 07:33 UTC, YourfriendRND commented
Внес рекомендуемые исправления. 
- рамок нет;
- наименование шрифтов исправил;

Нашел один момент, который по-моему мнению не работает и я не знаю как его исправить. 
На странице каталога, при наведении на товар появляются кнопки в закладки и купить. 
На кнопке "В Закладке" при ее нажатии появляется тень от рамки (или от текста не совсем понятно). У меня при нажатии она не появляется. 
Прошу проверить и дать рекомендации, что сделать и как решить. 
Заранее спасибо!

2020-10-05 21:19 UTC, merged

2020-10-05 21:21 UTC, lipa88-mk commented
Да, супер, теперь всё отлично и можно идти дальше! По поводу кнопки - да, там и правда есть тень, она описана в правиле .to-bookmarks:hover {filter: drop-shadow(0px 4px 4px var(--shadow-black));} строчка 553. В макете ее нет, возможно случайно скопировалась