Добавление графики
htmlacademy-htmlcss/1542653-technomart-29 pull request #6
Opened 2020-10-06 09:17 UTC by YourfriendRND

1) Экспортиовал графику: изображения и иконки. 
2) Добавил контентную графику в верстку.
Вопросы:
- Иконки другого цвета (которые меняют свой фоновый цвет при наведении) также нужно экспортировать? или цвет их можно изменить через стили? 
- В блоке слайдер не уверен, что это контентные изображения (дрели, перфораторы), больше похоже на фоновое. Т.е. пришла мысль вставить их 
фоновым изображением через стили и тогда будет виден текст на них. Если так и нужно сделать, то скажи, пожалуйста. Я их уберу и вставлю в задании
где будет оформление страницы.
В целом, считаю, что готово и жду комментарии.
Спасибо!

2020-10-06 12:37 UTC, lipa88-mk requested changes
По заданию - да, картинки есть, верно. Пара моментов:
1. в названиях файлов не должно быть знака пробела, вместо него можно "-", "_" и вместо кириллических символов только латиница. Лчше даже всегда с маленькой буквы - это не обязательное требование, просто так обычно удобнее, что всё написано только маленькими буквами, не путаешься
2. картинки, где предполагается изменение цвета самой картинки при наведении/клике (например лупа в поиске в шапке, стрелка у кнопки Войти), лучше всего делать svg, так как для них можно использовать стили, это будет чуть позже. 
3. в иконках соцсетей в подвале сама иконка белая и при наведении/клике цвет не меняется, меняется только фон. Поэтому лучше будет сделать только 1 версию vk, fb, insta без круга, только белые логотипы, и менять цвет круга под ними стилями. Про это тоже будет чуть позже.
4. По поводу слайдера - можно и так, и так. Оба варианта имеют место быть. С точки зрения контентных-декоративных изображений они и правда скорее фон. Но с точки зрения  дальнейшей поддержки сайта и их загрузки через CMS - могут быть и контентными. На данном этапе наверно и правда лучше будет сделать их фоновыми, чтобы не усложнять.

2020-10-06 12:37 UTC, lipa88-mk commented on catalog.html
> +                    <img src="img/логотип.svg" width="220" height="47" alt="Логотип интернет-магазина Техномарт">
все названия нужно делать только латиницей и без пробелов. Так как иначе могут потом быть проблемы при размещении на хостинге.

2020-10-06 20:15 UTC, YourfriendRND commented
- Изменил названия в соответствии с рекомендациями. Постарался соблюдать все рекомендации, прислушиваясь и перенимая опыт. Если считаешь, что так лучше и удобнее, то я считаю, что этому лучше научиться сразу. 
- Иконки соц. сетей заменил. Примерно понимаю как нужно будет сделать в следующем задании. 
- В слайдере убрал изображения сейчас. Вставлю через стили в следующем задании.

2020-10-07 10:52 UTC, merged

2020-10-07 10:55 UTC, lipa88-mk commented
Да, хорошо. Еще хотела добавить - если в процессе появляются вопросы - то их можно задавать и до отправки задания :)
По картинкам в дальнейшем когда будет пройдено еще несколько тем, возможно какие-то захочется заменить/переделать - это нормально